import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        surface: "#ede8de",
        "surface-dim": "#dfd8cb",
        "surface-card": "#f3efe6",
        "surface-container": "#eee8de",
        "surface-container-high": "#e4dfd3",
        "surface-container-lowest": "#ece7dc",
        "surface-biscuit": "#eae5db",
        "canvas-base": "#e8e3d8",
        "canvas-soft": "#ece7dc",
        "canvas-taupe": "#dfd8cb",
        primary: "#B40039",
        "primary-hover": "#8e002c",
        "primary-light": "#d62058",
        "primary-container": "#9b0031",
        "crimson-brand": "#B40039",
        "crimson-hover": "#8e002c",
        "crimson-wash": "rgba(180, 0, 57, 0.08)",
        "crimson-border": "rgba(180, 0, 57, 0.25)",
        "oxford-navy": "#B40039",
        "oxford-navy-wash": "#fee2e2",
        ink: "#21201d",
        "ink-body": "#3c3933",
        "ink-muted": "#575249",
        "ink-subtle": "#797368",
        "racing-green": "#2c5e43",
        "racing-green-wash": "#e2ebd9",
        "terracotta-rust": "#9e2a2b",
        "terracotta-wash": "#f5e4e2",
        "warm-border": "#d6cfc2",
        "warm-border-light": "#e2dbcf",
        "border-muted": "#c9c1b2",
        "border-earthy": "#d6cfc2",
        "chain-eth": "#627EEA",
        "chain-bsc": "#F0B90B",
        "chain-tron": "#FF060A",
        "badge-green-bg": "#e2ebd9",
        "badge-green-text": "#214a34",
        "badge-green-border": "#bdd6bc",
        "badge-amber-bg": "#f7eedb",
        "badge-amber-text": "#7d4a13",
        "badge-amber-border": "#e8d2ab",
        "badge-red-bg": "#f8e3e1",
        "badge-red-text": "#872021",
        "badge-red-border": "#ebb6b4",
      },
      fontFamily: {
        sans: ["'Inter'", "-apple-system", "BlinkMacSystemFont", "'Segoe UI'", "Roboto", "sans-serif"],
        display: ["'Plus Jakarta Sans'", "'Inter'", "-apple-system", "sans-serif"],
        serif: ["'Plus Jakarta Sans'", "'Inter'", "-apple-system", "sans-serif"],
        mono: ["'JetBrains Mono'", "monospace"],
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.375rem",
        xl: "0.5rem",
        full: "9999px",
      },
      boxShadow: {
        xs: "0 1px 2px rgba(40, 30, 20, 0.05)",
        sm: "0 1px 3px rgba(40, 30, 20, 0.08)",
      },
    },
  },
  plugins: [],
};
export default config;
